server:
  port: 8088

logging:
  config: classpath:log4j2.yml
  level:
    org.springframework.web: info

spring:
  aop:
    auto: true
    proxy-target-class: true
  jpa:
    database: mysql
    show-sql: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/grrs?characterEncoding=utf-8&useSSL=false&autoReconnect=true&createDatabaseIfNotExist=true
    username: root
    password: 123456